### ISSUE TITLE
Can't launch app: previous incarnation stops displaying but is still running

### ISSUE THREAD

**Issue by wtfrank** [SpeedProg/PveLauncher#3]
I haven't yet been able to figure out what triggers this, but I regularly find that the app UI is no longer present, but there is still a PveLauncher.exe process running. Once this process is killed its possible to relaunch the app.

**Comment by SpeedProg** [comment]
did you ever look at your tray? the app minimizes to tray if you click minimize, where you get it back from by double clicking. That is intended and was requested by the one I wrote it for.

**Comment by wtfrank** [comment]
I didnt know it could minimise to the tray, and in fact I've never clicked the minimise button. Weirdly this issue hasn't happened for 2 days now (before it was several times an evening). I will update this ticket next time it actually happens.

**Comment by wtfrank** [comment]
Ok I'm convinced now that your explanation is correct - every time that the app won't start it turns out its in the system tray.

I would say there's a problem but its not what I thought it was: when the app is minimised to the system tray, attempting to launch the app appears to do nothing. Other apps would usually restore the window under these circumstances.

**Comment by SpeedProg** [comment]
:D probably but I will cease developing this app anyway, everything it can do is provided by the New Eve Launcher that is currently in beta
